sudo: required

language: java

services:
  - docker

branches:
  only:
    - travis

notifications:
  email: false
  slack:
    secure: BYbxq0DiCsuXeFpECm5ZtW49WVHuT8GShLd3x1YyVv6CZFAAghFeuhEtdLrg3vmQAHYLOwZB8LFr8IfvdzUPZSWd/hA2QM0SVr6FD8MhfPeoDwxVjMD4SWpOSF5v+c1X8vVrj6EObnVX7E33kdzwac/QoIGuwHcd/TFzYCXOzDWVqaHYsQMqay8C8hL3ZnNOPLecvxDiX9U1Kxu1NZTOanCnsoX5C2Frr1HFbsYCz66gtO4thAjKNKw5TlbYDijSMbgfsAL+8WYJUCGyQZox173jpthxKWRQRQ09B+weU1NHAxgV8NTB0/wuNQhcX+EL1Ha4u1KtD8kVWUyb60bSWwHS9nKohK1E0eQnCUndlrrCAqwhswh9oWN2MLcfe1lwrDSw2cXY62iQY264MTI32oqMlAvz3oEeU8BzyKXlRo51IFb0ovhcIfoMXNEo0HqPMiE6PWgDmI5WVoJLjNAenaOOUlNFYZ3gF3Ox2whHnyRdAYZNBcBQBTk+64yR33qTD/z1QDgZ9K9K4UJgQWkJFw/klUxnLp/OZGj0WnIG+fggLJ4b8pu2eyt8zXyiPg/uKsLP8SfCExs7K70Ki5/VzJq/uTJkX8lw/GCv6OooEYrVKfVaIlFGG3J2Vl8OuRPFLTk9UKJUloRi3zasKupZzJDInfy6e40AzKIae9MozNE=

before_install:
  - mvn clean package
  - docker build -t patrykks/iosr-parking-lot-service .
  - docker run --name parkinglotservice -d patrykks/iosr-parking-lot-service

script:
  - docker ps | grep -q parkinglotservice
  - docker exec parkinglotservice mvn -f /webapp/parking-lot-service/pom.xml test

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push patrykks/iosr-parking-lot-service;
    fi