sudo: required

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker

branches:
  only:
    - travis

notifications:
  email: false
  slack:
    secure: BYbxq0DiCsuXeFpECm5ZtW49WVHuT8GShLd3x1YyVv6CZFAAghFeuhEtdLrg3vmQAHYLOwZB8LFr8IfvdzUPZSWd/hA2QM0SVr6FD8MhfPeoDwxVjMD4SWpOSF5v+c1X8vVrj6EObnVX7E33kdzwac/QoIGuwHcd/TFzYCXOzDWVqaHYsQMqay8C8hL3ZnNOPLecvxDiX9U1Kxu1NZTOanCnsoX5C2Frr1HFbsYCz66gtO4thAjKNKw5TlbYDijSMbgfsAL+8WYJUCGyQZox173jpthxKWRQRQ09B+weU1NHAxgV8NTB0/wuNQhcX+EL1Ha4u1KtD8kVWUyb60bSWwHS9nKohK1E0eQnCUndlrrCAqwhswh9oWN2MLcfe1lwrDSw2cXY62iQY264MTI32oqMlAvz3oEeU8BzyKXlRo51IFb0ovhcIfoMXNEo0HqPMiE6PWgDmI5WVoJLjNAenaOOUlNFYZ3gF3Ox2whHnyRdAYZNBcBQBTk+64yR33qTD/z1QDgZ9K9K4UJgQWkJFw/klUxnLp/OZGj0WnIG+fggLJ4b8pu2eyt8zXyiPg/uKsLP8SfCExs7K70Ki5/VzJq/uTJkX8lw/GCv6OooEYrVKfVaIlFGG3J2Vl8OuRPFLTk9UKJUloRi3zasKupZzJDInfy6e40AzKIae9MozNE=

before_install:
  - docker build -t builder_image -f docker/Dockerfile.buidler .
  - docker run -it --rm -v $(pwd):/microservice -v $HOME/.m2:/root/.m2 builder_image
  - docker build -t dist_image -f docker/Dockerfile.dist .
  - docker build -t test_image -f docker/Dockerfile.test .

script:
  - docker run -it -v $HOME/.m2:/root/.m2 --name test test_image
  - docker run -d --name dist dist_image
  - docker ps | grep -q dist

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag dist_image patrykks/iosr-parking-lot-service;
    docker push patrykks/iosr-parking-lot-service;
    fi