FROM maven:3-jdk-8-slim
COPY "target/parking-lot-service-1.0-SNAPSHOT.jar" "/webapp/"
EXPOSE 5555
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /webapp/parking-lot-service-1.0-SNAPSHOT.jar $APP_OPTS" ]

